server:
  port: 8080
spring:
  application:
    name: "InvoiceManagement"
  devtools:
    add-properties: false
  datasource:
    postgresql:
      url: "jdbc:postgresql://localhost:5432/invoice_management"
      username: "admin"
      password: "secret"
      driverClassName: "org.postgresql.Driver"
    oracle:
      url: "jdbc:oracle:thin:@localhost:1521/FREEPDB1"
      username: "adminuser"
      password: "adminpass"
      driverClassName: "oracle.jdbc.OracleDriver"
  jpa:
      hibernate:
        ddl-auto: "update"
      postgresql:
        databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
      oracle:
        databasePlatform: org.hibernate.dialect.OracleDialect
      h2:
        console:
          enabled: false
          path: "/h2"
      profiles:
        include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
