server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: InvoiceManagement
  devtools:
    add-properties: false

  datasource:
    postgresql:
      url: ${DB_POSTGRES_URL:jdbc:postgresql://localhost:5432/invoice_management}
      username: ${DB_POSTGRES_USER:admin}
      password: ${DB_POSTGRES_PASS:secret}
      driver-class-name: org.postgresql.Driver

    oracle:
      url: ${DB_ORACLE_URL:jdbc:oracle:thin:@localhost:1521/INVOICE_DB}
      username: ${DB_ORACLE_USER:PRUEBA}
      password: ${DB_ORACLE_PASS:ADMINPASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver
      procedure:
        schema: ${ORACLE_PROCEDURE_SCHEMA:PRUEBA}
        name: ${ORACLE_PROCEDURE_NAME:INSERT_INVOICE}
        array-types:
          varchar2-list: ${ORACLE_VARCHAR2_LIST:PRUEBA.VARCHAR2_LIST}
          number-list: ${ORACLE_NUMBER_LIST:PRUEBA.NUMBER_LIST}
          float-list: ${ORACLE_FLOAT_LIST:PRUEBA.FLOAT_LIST}


  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    postgresql:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    oracle:
      database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        show_sql: false
        format_sql: false

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200,http://localhost:3000}

adapter:
  restconsumer:
    base-url: ${EXTERNAL_INVOICE_SERVICE_URL:http://localhost:8000/api/v1}
    connect-timeout-ms: ${CONNECT_TIMEOUT_MS:5000}
    read-timeout-ms: ${READ_TIMEOUT_MS:10000}

